### ISSUE TITLE
example/cxx/dense/framk_mpi が eigen_exa の場合 dimension > 60 で落ちる

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#208]
Intel+MKL, MacOS X, gcc+lapack, sekirei、全て落ちる

**Comment by t-sakashita** [comment]
sekireiでも落ちる。

**Comment by t-sakashita** [comment]
phi@Kobeにて
```
mpirun -np 1 xterm -e gdb ./frank_mpi eigen_exa:tri 100
```
出力：
```
Starting program: /home/sakashita/build/rokko/benchmark/use_rokko/dense_frank_mpi/frank_mpi eigen_exa:tri 100
[Thread debugging using libthread_db enabled]
Eigenvalue decomposition of Frank matrix
library = eigen_exa
routine = tri
dimension = 100
[New Thread 0x2aaac3c81700 (LWP 6842)]
[New Thread 0x2aaac83ff740 (LWP 6843)]
[New Thread 0x2aaac8800780 (LWP 6844)]
[New Thread 0x2aaad43ff7c0 (LWP 6845)]
 Scaling factor =    1.00000000000000     
*** glibc detected *** /home/sakashita/build/rokko/benchmark/use_rokko/dense_frank_mpi/frank_mpi: realloc(): invalid pointer: 0x00000000006e2270 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x2aaad43ff7c0 (LWP 6845)]
0x000000390ce32625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-33.el6.x86_64 libX11-1.6.0-2.2.el6.x86_64 libXau-1.0.6-4.el6.x86_64 libcom_err-1.41.12-21.el6.x86_64 libgcc-4.4.7-11.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64 libxcb-1.9.1-2.el6.x86_64 openssl-1.0.1e-30.el6_6.2.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x000000390ce32625 in raise () from /lib64/libc.so.6
#1  0x000000390ce33e05 in abort () from /lib64/libc.so.6
#2  0x000000390ce70537 in __libc_message () from /lib64/libc.so.6
#3  0x000000390ce75e66 in malloc_printerr () from /lib64/libc.so.6
#4  0x000000390ce7bcf2 in realloc () from /lib64/libc.so.6
#5  0x000000390ca11415 in _dl_update_slotinfo ()
   from /lib64/ld-linux-x86-64.so.2
#6  0x000000390ca115ed in __tls_get_addr () from /lib64/ld-linux-x86-64.so.2
#7  0x00002aaaaef3db2d in __kmp_api_omp_get_thread_num ()
    at ../../src/kmp_ftn_entry.h:437
#8  0x00002aaaac627633 in mkl_lapack_dlaed0 ()
   from /home/issp/intel/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_intel_thread.so
#9  0x00002aaaaef7dab3 in __kmp_invoke_microtask ()
   from /home/issp/intel/composer_xe_2015.3.187/compiler/lib/intel64/libiomp5.so
#10 0x00002aaaaef529d7 in __kmp_invoke_task_func (gtid=6837)
    at ../../src/kmp_runtime.c:7069
#11 0x00002aaaaef520da in __kmp_launch_thread (this_thr=0x1ab5)
    at ../../src/kmp_runtime.c:5625
#12 0x00002aaaaef7ddad in __kmp_launch_worker (thr=0x1ab5)
    at ../../src/z_Linux_util.c:786
#13 0x000000390d6079d1 in start_thread () from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
#14 0x000000390cee89dd in clone () from /lib64/libc.so.6
(gdb)
```

**Comment by t-sakashita** [comment]
スレッド関係？
OpenMPを使わず、`-mkl=serial'でビルドしてみるか。

**Comment by t-sakashita** [comment]
Rokkoの中に作った、no_rokkoなサンプルでもエラーは出ない。
```
cd benchmark/no_rokko/dense_frank_mpi
mpirun -np 4 ./eigen_exa 200
```

**Comment by t-sakashita** [comment]
最新版2.3dには、シェアードライブラリ作成のためのパッチがあるので、それで試してみる。

**Comment by t-sakashita** [comment]
EigenExa2.3dの付属サンプル
* phi@Kobeでは、最初にsegfault
* zetta(GNU+rpmのScaLAPACK+BLAS)では、動く。

**Comment by t-sakashita** [comment]
Mvapich2ではなく、Intel MPIでやってみる。

**Comment by t-sakashita** [comment]
EigenExaを静的コンパイルした場合
```
ld: /home/sakashita/try/EigenExa-2.3d/install_root/lib/libEigenExa.a(eigen_sx.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile wit
```

**Comment by t-sakashita** [comment]
phi@Kobeにて
EigenExa2.3dをRokkoから使った場合のエラー
```
mpirun -np 1 xterm -e idb ./frank_mpi
```

```
(gdb) run eigen_exa:penta 100
Starting program: /home/sakashita/build/rokko-intelmpi/example/cxx/dense/frank_mpi eigen_exa:penta 100
[Thread debugging using libthread_db enabled]
Eigenvalue decomposition of Frank matrix
library:routine = eigen_exa:penta
num_procs = 1
num_threads per process = 4
routine = penta
dimension = 100
[New Thread 0x2aaac2435700 (LWP 12265)]
[New Thread 0x2aaac2835740 (LWP 12266)]
[New Thread 0x2aaac2c36780 (LWP 12267)]
[New Thread 0x2aaad03ff7c0 (LWP 12268)]

Program received signal SIGFPE, Arithmetic exception.
0x00002aaab016546b in numroc_ ()
   from /home/issp/intel/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_scalapack_lp64.so
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6.x86_64 libgcc-4.4.7-11.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64
(gdb) bt
#0  0x00002aaab016546b in numroc_ ()
   from /home/issp/intel/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_scalapack_lp64.so
#1  0x00002aaab06fcf28 in my_pdsxedc_ ()
   from /home/sakashita/try/EigenExa-2.3d/install_root/lib/libEigenExa.so
#2  0x00002aaab06f0aa1 in eigen_dcx_ ()
   from /home/sakashita/try/EigenExa-2.3d/install_root/lib/libEigenExa.so
#3  0x00002aaab07154d0 in eigen_sx_ ()
   from /home/sakashita/try/EigenExa-2.3d/install_root/lib/libEigenExa.so
#4  0x00002aaaaad0266b in ROKKO_eigen_exa_sx (n=100, nvec=100, a=0x6c4040, 
    lda=112, w=0x6ff5c0, z=0x6ff8f0, ldz=112, m_forward=48, m_backward=128, 
    mode=65 'A')
    at /home/sakashita/development/rokko/rokko/eigen_exa/eigen_exa_sx.c:17
#5  0x00002aaaaad05756 in rokko::eigen_exa::diagonalize_eigen_sx (mat=..., 
    eigvals=..., eigvecs=..., params=...)
    at /home/sakashita/development/rokko/rokko/eigen_exa/diagonalize_eigen_sx.hpp:40
#6  0x00002aaaaad0762c in rokko::eigen_exa::solver::diagonalize (
    this=0x6c2228, mat=..., eigvals=..., eigvecs=..., params=...)
    at /home/sakashita/development/rokko/rokko/eigen_exa/core.hpp:63
#7  0x00002aaaaad03433 in rokko::detail::pd_solver_wrapper<rokko::eigen_exa::solver>::diagonalize (this=0x6c2220, mat=..., eigvals=..., eigvecs=..., 
    params=...)
---Type <return> to continue, or q <return> to quit---
    at /home/sakashita/development/rokko/rokko/parallel_dense_ev.hpp:76
#8  0x000000000043e1e3 in rokko::parallel_dense_ev::diagonalize (
    this=0x7fffffffc1f8, mat=..., eigvals=..., eigvecs=...)
    at /home/sakashita/development/rokko/rokko/parallel_dense_ev.hpp:139
#9  0x0000000000428315 in main (argc=3, argv=0x7fffffffca98)
    at /home/sakashita/development/rokko/example/cxx/dense/frank_mpi.cpp:65
```

**Comment by t-sakashita** [comment]
静的ライブラリで全て作成すれば、EigenExaの中のエラー行がわかるはず。

**Comment by t-sakashita** [comment]
EigenExa2.2b
動的ライブラリのままでも、エラー発生箇所がわかった。
```
(gdb) run eigen_exa 100
Starting program: /home/sakashita/build/rokko-intelmpi/example/cxx/dense/frank_mpi eigen_exa 100
[Thread debugging using libthread_db enabled]
Eigenvalue decomposition of Frank matrix
library:routine = eigen_exa
num_procs = 1
num_threads per process = 4
routine = 
dimension = 100
[New Thread 0x2aaac2d18700 (LWP 29392)]
[New Thread 0x2aaac3118740 (LWP 29393)]
[New Thread 0x2aaac3519780 (LWP 29394)]
[New Thread 0x2aaacc3ff7c0 (LWP 29395)]

Program received signal SIGSEGV, Segmentation fault.
0x00002aaab0a142c4 in init_resource ()
   from /home/materiapps/rokko/eigenexa-2.2b-2/Debug/lib/libEigenExa.so
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6.x86_64 libgcc-4.4.7-11.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64 numactl-2.0.9-2.el6.x86_64
(gdb) bt
#0  0x00002aaab0a142c4 in init_resource ()
   from /home/materiapps/rokko/eigenexa-2.2b-2/Debug/lib/libEigenExa.so
#1  0x00002aaab0a1421c in reentrancy_init ()
   from /home/materiapps/rokko/eigenexa-2.2b-2/Debug/lib/libEigenExa.so
#2  0x00002aaab0a13ead in for__once_private ()
   from /home/materiapps/rokko/eigenexa-2.2b-2/Debug/lib/libEigenExa.so
#3  0x00002aaabe33fcde in for__acquire_lun ()
   from /home/issp/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifcore.so.5
#4  0x00002aaabe39e7f2 in flushqq_ ()
   from /home/issp/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifcore.so.5
#5  0x00002aaab098522c in eigen_prd (n=100, a=..., nma0=112, d_out=..., 
    e_out=..., nme0=100, m_orig=48)
    at /home/wistaria/build/EigenExa-2.2b/eigen_prd.F:41
#6  0x00002aaab09c6b89 in eigen_sx (n=100, nvec=100, a=..., lda=112, w=..., 
    z=..., ldz=112, m_forward=48, m_backward=128, mode='A', 
    .tmp.MODE.len_V$4d=140733193388132)
    at /home/wistaria/build/EigenExa-2.2b/eigen_sx.F:66
#7  0x00002aaaaad0265f in ROKKO_eigen_exa_sx (n=100, nvec=100, a=0x6c3220, 
    lda=112, w=0x6fe9d0, z=0x6fed00, ldz=112, m_forward=48, m_backward=128, 
    mode=65 'A')
    at /home/sakashita/development/rokko/rokko/eigen_exa/eigen_exa_sx.c:17
---Type <return> to continue, or q <return> to quit---
#8  0x00002aaaaad0574a in rokko::eigen_exa::diagonalize_eigen_sx (mat=..., 
    eigvals=..., eigvecs=..., params=...)
    at /home/sakashita/development/rokko/rokko/eigen_exa/diagonalize_eigen_sx.hpp:40
#9  0x00002aaaaad07620 in rokko::eigen_exa::solver::diagonalize (
    this=0x6c26c8, mat=..., eigvals=..., eigvecs=..., params=...)
    at /home/sakashita/development/rokko/rokko/eigen_exa/core.hpp:63
#10 0x00002aaaaad03427 in rokko::detail::pd_solver_wrapper<rokko::eigen_exa::solver>::diagonalize (this=0x6c26c0, mat=..., eigvals=..., eigvecs=..., 
    params=...)
    at /home/sakashita/development/rokko/rokko/parallel_dense_ev.hpp:76
#11 0x000000000043e303 in rokko::parallel_dense_ev::diagonalize (
    this=0x7fffffffbc48, mat=..., eigvals=..., eigvecs=...)
    at /home/sakashita/development/rokko/rokko/parallel_dense_ev.hpp:139
#12 0x0000000000428435 in main (argc=3, argv=0x7fffffffc4e8)
    at /home/sakashita/development/rokko/example/cxx/dense/frank_mpi.cpp:6
```

**Comment by t-sakashita** [comment]
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/540673

**Comment by t-sakashita** [comment]
EigenExa2.2bとEigenExa2.3dでエラーの種類が違う。

**Comment by t-sakashita** [comment]
CMakeLists.txtを作成してEigenExa2.3dをインストール
EigenExa2.3dの中でのエラー発生箇所がわかった。
```
(gdb) run eigen_exa:penta 100
Starting program: /home/sakashita/build/rokko-intelmpi/example/cxx/dense/frank_mpi eigen_exa:penta 100
[Thread debugging using libthread_db enabled]
Eigenvalue decomposition of Frank matrix
library:routine = eigen_exa:penta
num_procs = 1
num_threads per process = 4
routine = penta
dimension = 100
[New Thread 0x2aaac254a700 (LWP 32204)]
[New Thread 0x2aaac294a740 (LWP 32205)]
[New Thread 0x2aaad03ff780 (LWP 32206)]
[New Thread 0x2aaacc3ff7c0 (LWP 32207)]

Program received signal SIGFPE, Arithmetic exception.
0x00002aaab016546b in numroc_ ()
   from /home/issp/intel/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_scalapack_lp64.so
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6.x86_64 libgcc-4.4.7-11.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64
(gdb) bt
#0  0x00002aaab016546b in numroc_ ()
   from /home/issp/intel/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_scalapack_lp64.so
#1  0x00002aaab070570a in my_pdsxedc (compz='I', hbw=2, n=100, d=..., e=..., 
    lde=100, q=..., iq=1, jq=1, descq=..., work=..., lwork=40601, iwork=..., 
    liwork=710, info=0, .tmp.COMPZ.len_V$2f=1)
    at /home/sakashita/build/EigenExa-2.3d/my_pdsxedc.F:168
#2  0x00002aaab070363b in eigen_dcx (n=100, d=..., e=..., lde=100, z=..., 
    ldz=112, info=0, ret=0) at /home/sakashita/build/EigenExa-2.3d/dcx.F:127
#3  0x00002aaab0731075 in eigen_sx (n=100, nvec=100, a=..., lda=112, w=..., 
    z=..., ldz=112, m_forward=48, m_backward=128, mode='A', 
    .tmp.MODE.len_V$56=140733193388132)
    at /home/sakashita/build/EigenExa-2.3d/eigen_sx.F:126
#4  0x00002aaaaad0267b in ROKKO_eigen_exa_sx (n=100, nvec=100, a=0x6cb040, 
    lda=112, w=0x7065c0, z=0x7068f0, ldz=112, m_forward=48, m_backward=128, 
    mode=65 'A')
    at /home/sakashita/development/rokko/rokko/eigen_exa/eigen_exa_sx.c:17
#5  0x00002aaaaad05766 in rokko::eigen_exa::diagonalize_eigen_sx (mat=..., 
    eigvals=..., eigvecs=..., params=...)
    at /home/sakashita/development/rokko/rokko/eigen_exa/diagonalize_eigen_sx.hpp:40
#6  0x00002aaaaad0763c in rokko::eigen_exa::solver::diagonalize (
    this=0x6c9228, mat=..., eigvals=..., eigvecs=..., params=...)
---Type <return> to continue, or q <return> to quit---
    at /home/sakashita/development/rokko/rokko/eigen_exa/core.hpp:63
#7  0x00002aaaaad03443 in rokko::detail::pd_solver_wrapper<rokko::eigen_exa::solver>::diagonalize (this=0x6c9220, mat=..., eigvals=..., eigvecs=..., 
    params=...)
    at /home/sakashita/development/rokko/rokko/parallel_dense_ev.hpp:76
#8  0x000000000043f153 in rokko::parallel_dense_ev::diagonalize (
    this=0x7fffffffc1f8, mat=..., eigvals=..., eigvecs=...)
    at /home/sakashita/development/rokko/rokko/parallel_dense_ev.hpp:139
#9  0x0000000000429285 in main (argc=3, argv=0x7fffffffca98)
    at /home/sakashita/development/rokko/example/cxx/dense/frank_mpi.cpp:65
```

**Comment by t-sakashita** [comment]
https://github.com/t-sakashita/rokko/issues/229のコミット
https://github.com/t-sakashita/rokko/commit/138ed1128ea8879963f3426920b030502e797ee5
でエラーは解消
