### ISSUE TITLE
C++で書いた行列・ベクトル積をPythonで与える。

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#370]
メインプログラムはPython。
* `distributed_mfree`クラスを継承したクラスを`py::object`によりPython側に渡す。
  * ラッパーの中で、`py::object`を継承したクラスにキャストすれば良いのか？
* `py::cpp_function`
  * C++ -> Python -> C++と制御を移す際に使う。Python側に渡ったときに関数の情報（引数の型）が失われないかを調べる？

Pythonパッケージ（ダイナミックライブラリ）のビルドは、pyrokko本体とは別に行うようにする。

**Comment by t-sakashita** [comment]
基底クラスで受けることができた。
heisenberg_mpiの固有値の計算結果は正しかった。
基底クラスをpybind11に登録すると、warningが出る。
```
In file included from /Users/sakashitatatsuya/development/rokko/rokko/pyrokko.cpp:12:
In file included from /Users/sakashitatatsuya/development/rokko/3rd-party/pybind11/include/pybind11/pybind11.h:49:
In file included from /Users/sakashitatatsuya/development/rokko/3rd-party/pybind11/include/pybind11/detail/../attr.h:13:
In file included from /Users/sakashitatatsuya/development/rokko/3rd-party/pybind11/include/pybind11/cast.h:13:
In file included from /Users/sakashitatatsuya/development/rokko/3rd-party/pybind11/include/pybind11/detail/../pytypes.h:12:
In file included from /Users/sakashitatatsuya/development/rokko/3rd-party/pybind11/include/pybind11/detail/common.h:140:
In file included from /opt/local/libexec/llvm-6.0/include/c++/v1/forward_list:171:
/opt/local/libexec/llvm-6.0/include/c++/v1/memory:2285:5: warning: delete called on 'rokko::distributed_mfree' that is abstract but has non-virtual
      destructor [-Wdelete-non-virtual-dtor]
    delete __ptr;
    ^
/opt/local/libexec/llvm-6.0/include/c++/v1/memory:2598:7: note: in instantiation of member function
      'std::__1::default_delete<rokko::distributed_mfree>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/opt/local/libexec/llvm-6.0/include/c++/v1/memory:2552:19: note: in instantiation of member function 'std::__1::unique_ptr<rokko::distributed_mfree,
      std::__1::default_delete<rokko::distributed_mfree> >::reset' requested here
  ~unique_ptr() { reset(); }
                  ^
/Users/sakashitatatsuya/development/rokko/3rd-party/pybind11/include/pybind11/pybind11.h:1352:40: note: in instantiation of member function
      'std::__1::unique_ptr<rokko::distributed_mfree, std::__1::default_delete<rokko::distributed_mfree> >::~unique_ptr' requested here
            v_h.holder<holder_type>().~holder_type();
                                       ^
/Users/sakashitatatsuya/development/rokko/3rd-party/pybind11/include/pybind11/pybind11.h:1081:26: note: in instantiation of member function
      'pybind11::class_<rokko::distributed_mfree>::dealloc' requested here
        record.dealloc = dealloc;
                         ^
/Users/sakashitatatsuya/development/rokko/rokko/pyrokko.cpp:251:3: note: in instantiation of function template specialization
      'pybind11::class_<rokko::distributed_mfree>::class_<>' requested here
  py::class_<distributed_mfree>(m, "distributed_mfree_ORIG");
  ^
```
これを抑えるpybind11のマクロ定義はあるか？

**Comment by t-sakashita** [comment]
以下のように、コンストラクタだけを登録すれば良い。
関数`multiply`は、登録しなくて良い。
```c++
  py::class_<heisenberg_op, rokko::distributed_mfree>(m, "mfree")
    .def(py::init<int, const std::vector<std::pair<int, int>>&>());
```

**Comment by t-sakashita** [comment]
同じクラスを登録する２つのPythonモジュールを作成すると、両方ともimportした場合にエラーとなる。
```
Traceback (most recent call last):
  File "heisenberg_mfree_from_cxx_class_mpi.py", line 14, in <module>
    import heisenberg
ImportError: generic_type: type "distributed_mfree_base" is already registered!
```

**Comment by t-sakashita** [comment]
Pythonバインディングの中で、pyrokkoをインポートすることにした。
```c++
  py::module::import("pyrokko");
```
使用するのは、pyrokkoは`"distributed_mfree_base"`のみであるが、当面はこれで対処する。

そうすると、pyrokkoにパスが通っていない場合にエラーとなるようにできた。
```python
import heisenberg
```
エラー内容：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ModuleNotFoundError: No module named 'pyrokko'
```

**Comment by t-sakashita** [comment]
Pythonバインディングを作成した。
このバインディングを使う例題として、heisenberg_mfreeのラッパーを追加した。
283625cfd48183d853c32acb596f4e55bed6cc0f

**Comment by t-sakashita** [comment]
例題として、laplacian_mfreeのラッパーとメインプログラムを追加した。
17482695b2cb10deae4d87cc3510d6fcb099b4e2
